### ISSUE TITLE
Warning: custom integration 'pollen_dk' accesses hass.helpers.discovery

### ISSUE THREAD

**Issue by HolgerMiara** [J-Lindvig/Pollen_DK#7]
Moin, 

I found following warning in my logs. It should be addressed before Home Assistant 2025.5. 

```yaml
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:324
First occurred: January 7, 2025 at 22:43:47 (2 occurrences)
Last logged: January 7, 2025 at 23:10:26

Detected that custom integration 'pollen_dk' accesses hass.helpers.discovery, which should be updated to import functions used from discovery directly at custom_components/pollen_dk/__init__.py, line 54: hass.helpers.discovery.async_load_platform(CONF_PLATFORM, DOMAIN, conf, config). This will stop working in Home Assistant 2025.5, please create a bug report at https://github.com/J-Lindvig/Pollen_DK/issues

``` 
Just as a heads-up =)

Cheers, 
Holger.
